name: Sync Livre → Org

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Pull from livre
        run: |
          git remote add source https://github.com/SurnumerismeAuthor/surnumerisme-livre.git || true
          git fetch source
          git reset --hard source/main
          # Assurer que le dossier existe (sans réécrire récursivement)
          mkdir -p .github/workflows
          # Mettre à jour le fichier uniquement s'il est absent ou modifié
          if [ ! -f .github/workflows/sync.yml ] || ! grep -q "Synchronisation automatique" .github/workflows/sync.yml; then
            cat > .github/workflows/sync.yml << 'EOF'
name: Sync Livre → Org
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - name: Pull from livre
        run: |
          git remote add source https://github.com/SurnumerismeAuthor/surnumerisme-livre.git || true
          git fetch source
          git reset --hard source/main
          mkdir -p .github/workflows
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changements détectés, passage à l'enregistrement."
          else
            echo "Aucun changement à enregistrer."
            exit 0
          fi
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Synchronisation automatique depuis surnumerisme-livre (main)" || echo "Aucun changement à enregistrer"
      - name: Push changes
        run: git push origin main
            EOF
          fi

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changements détectés, passage à l'enregistrement."
          else
            echo "Aucun changement à enregistrer."
            exit 0
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Synchronisation automatique depuis surnumerisme-livre (main)" || echo "Aucun changement à enregistrer"

      - name: Push changes
        run: git push origin main
